version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flatclub-backend
    volumes:
      - sqlite-data:/data
    environment:
      DATABASE_URL: sqlite:///./data/test.db
    ports:
      - "8000:8000"
    command: >
      sh -c "if [ ! -f /data/test.db ]; then
               mkdir -p /data &&
               chmod 777 /data &&
               python app/create_db.py &&
               python app/seed_data.py;
             fi &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: ./my-project
      dockerfile: Dockerfile
    container_name: flatclub-frontend
    # volumes:
    #   - ./my-project:/app
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  sqlite-data:
