"""Add quiet_hours to users

Revision ID: 51fe2f7d1b21
Revises: 78fbe3d1f715
Create Date: 2025-01-08 20:12:42.316030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51fe2f7d1b21'
down_revision: Union[str, None] = '78fbe3d1f715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
